trigger:
  branches:
    include:
    - master
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: corvus-dotnet-github

jobs:
- template: templates/build.and.release.yml@recommended_practices
  parameters:
    vmImage: 'ubuntu-latest'
    service_connection_nuget_org: $(Endjin_Service_Connection_NuGet_Org)
    service_connection_github: $(Endjin_Service_Connection_GitHub)
    solution_to_build: $(Endjin_Solution_To_Build)
    postCustomEnvironmentVariables:
      - powershell: |
          Write-Host "##vso[task.setvariable variable=AzureServicesAuthConnectionString]$Env:ENDJIN_AZURESERVICESAUTHCONNECTIONSTRING"
          Write-Host "##vso[task.setvariable variable=RootTenantBlobStorageConfigurationOptions__AccountName]$Env:ENDJIN_AZURESTORAGECONNECTIONSTRING"
          Write-Host "##vso[task.setvariable variable=RootTenantCosmosConfigurationOptions__AccountUri]$Env:ENDJIN_COSMOSDBACCOUNTURI"
          Write-Host "##vso[task.setvariable variable=RootTenantCosmosConfigurationOptions__AccountKeySecretName]$Env:ENDJIN_COSMOSACCOUNTKEYSECRETNAME"
          Write-Host "##vso[task.setvariable variable=RootTenantCosmosConfigurationOptions__KeyVaultName]$Env:ENDJIN_KEYVAULTNAME"
          Write-Host "##vso[task.setvariable variable=RootTenantGremlinConfigurationOptions__HostName]$Env:ENDJIN_COSMOSDBGREMLINHOSTNAME"
          Write-Host "##vso[task.setvariable variable=RootTenantGremlinConfigurationOptions__Port]$Env:ENDJIN_COSMOSDBGREMLINPORT"
          Write-Host "##vso[task.setvariable variable=RootTenantGremlinConfigurationOptions__AuthKeySecretName]$Env:ENDJIN_COSMOSDBGREMLINACCOUNTKEYSECRETNAME"
          Write-Host "##vso[task.setvariable variable=RootTenantGremlinConfigurationOptions__KeyVaultName]$Env:ENDJIN_KEYVAULTNAME"
        displayName: 'Set Custom Environment Variables'
        env:
          ENDJIN_AZURESERVICESAUTHCONNECTIONSTRING: $(Endjin_AzureServicesAuthConnectionString)
          ENDJIN_AZURESTORAGECONNECTIONSTRING: $(Endjin_AzureStorageConnectionString)
          ENDJIN_COSMOSDBACCOUNTURI: $(Endjin_CosmosDbAccountUri)
          ENDJIN_COSMOSACCOUNTKEYSECRETNAME: $(Endjin_CosmosDbKeySecretName)
          ENDJIN_KEYVAULTNAME: $(Endjin_KeyVaultName)