trigger:
  branches:
    include:
    - master
    - main
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: corvus-dotnet-github
      ref: refs/heads/feature/scripted-build

jobs:
- template: templates/build.and.release.scripted.yml@recommended_practices
  parameters:
    vmImage: 'ubuntu-latest'
    service_connection_nuget_org: $(Endjin_Service_Connection_NuGet_Org)
    service_connection_github: $(Endjin_Service_Connection_GitHub)
    solution_to_build: $(Endjin_Solution_To_Build)
    postCustomEnvironmentVariables:
      - powershell: |
          Write-Host "##vso[task.setvariable variable=AzureServicesAuthConnectionString]$Env:ENDJIN_AZURESERVICESAUTHCONNECTIONSTRING"
          Write-Host "##vso[task.setvariable variable=TestSettings__AzureStorageConnectionString]$Env:ENDJIN_AZURESTORAGECONNECTIONSTRING"
          Write-Host "##vso[task.setvariable variable=TenancyBlobStorageConfigurationOptions__AccountName]$Env:ENDJIN_AZURESTORAGECONNECTIONSTRING"
          Write-Host "##vso[task.setvariable variable=TestBlobStorageConfigurationOptions__AccountName]$Env:ENDJIN_AZURESTORAGECONNECTIONSTRING"
          Write-Host "##vso[task.setvariable variable=TestTableStorageConfigurationOptions__AccountName]$Env:ENDJIN_AZURESTORAGECONNECTIONSTRING"
          Write-Host "##vso[task.setvariable variable=TestCosmosConfigurationOptions__AccountUri]$Env:ENDJIN_COSMOSDBACCOUNTURI"
          Write-Host "##vso[task.setvariable variable=TestCosmosConfigurationOptions__AccessKeyInKeyVault__VaultName]$Env:ENDJIN_KEYVAULTNAME"
          Write-Host "##vso[task.setvariable variable=TestCosmosConfigurationOptions__AccessKeyInKeyVault__SecretName]$Env:ENDJIN_COSMOSACCOUNTKEYSECRETNAME"
          Write-Host "##vso[task.setvariable variable=TestLegacyCosmosConfigurationOptions__AccountUri]$Env:ENDJIN_COSMOSDBACCOUNTURI"
          Write-Host "##vso[task.setvariable variable=TestLegacyCosmosConfigurationOptions__AccountKeySecretName]$Env:ENDJIN_COSMOSACCOUNTKEYSECRETNAME"
          Write-Host "##vso[task.setvariable variable=TestLegacyCosmosConfigurationOptions__KeyVaultName]$Env:ENDJIN_KEYVAULTNAME"
          Write-Host "##vso[task.setvariable variable=TestGremlinConfigurationOptions__HostName]$Env:ENDJIN_COSMOSDBGREMLINHOSTNAME"
          Write-Host "##vso[task.setvariable variable=TestGremlinConfigurationOptions__Port]$Env:ENDJIN_COSMOSDBGREMLINPORT"
          Write-Host "##vso[task.setvariable variable=TestGremlinConfigurationOptions__AuthKeySecretName]$Env:ENDJIN_COSMOSDBGREMLINACCOUNTKEYSECRETNAME"
          Write-Host "##vso[task.setvariable variable=TestGremlinConfigurationOptions__KeyVaultName]$Env:ENDJIN_KEYVAULTNAME"
        displayName: 'Set Custom Environment Variables'
        env:
          ENDJIN_AZURESERVICESAUTHCONNECTIONSTRING: $(Endjin_AzureServicesAuthConnectionString)
          ENDJIN_AZURESTORAGECONNECTIONSTRING: $(Endjin_AzureStorageConnectionString)
          ENDJIN_COSMOSDBACCOUNTURI: $(Endjin_CosmosDbAccountUri)
          ENDJIN_COSMOSACCOUNTKEYSECRETNAME: $(Endjin_CosmosDbKeySecretName)
          ENDJIN_KEYVAULTNAME: $(Endjin_KeyVaultName)
    netSdkVersion: '3.x'